/**
 * @file main.cpp
 * @brief 相控阵雷达回波模拟器 V3.0 主程序
 * @author Generated by Claude
 * @date 2026-03-13
 *
 * 使用方法:
 *   RadarApp [配置文件路径]
 *
 * 示例:
 *   RadarApp ../config/simulation_config.txt
 */

#include "RadarSimulator.h"
#include "Logger.h"
#include <iostream>
#include <string>
#include <csignal>

// 全局模拟器指针（用于信号处理）
static PhasedArrayRadarSimulator* g_simulator = nullptr;

// 信号处理函数
void signalHandler(int signum) {
    LOG_WARN("Interrupt signal received: " + std::to_string(signum));
    if (g_simulator) {
        g_simulator->stop();
    }
}

/**
 * @brief 打印使用说明
 */
void printUsage(const char* programName) {
    std::cout << "Usage: " << programName << " [config_file]" << std::endl;
    std::cout << std::endl;
    std::cout << "Arguments:" << std::endl;
    std::cout << "  config_file    Path to simulation configuration file" << std::endl;
    std::cout << "                 (default: ../config/simulation_config.txt)" << std::endl;
    std::cout << std::endl;
    std::cout << "Example:" << std::endl;
    std::cout << "  " << programName << " ../config/simulation_config.txt" << std::endl;
}

/**
 * @brief 打印欢迎信息
 */
void printWelcome() {
    std::cout << "========================================" << std::endl;
    std::cout << "  Phased Array Radar Echo Simulator" << std::endl;
    std::cout << "  Version 3.0" << std::endl;
    std::cout << "========================================" << std::endl;
    std::cout << std::endl;
}

/**
 * @brief 主函数
 */
int main(int argc, char* argv[]) {
    printWelcome();

    // 设置日志文件
    Logger::getInstance().setLogFile("../out/logs/simulation.log");
    Logger::getInstance().setLevel(Logger::Level::INFO);

    // 确定配置文件路径
    std::string configPath = "../config/simulation_config.txt";
    if (argc > 1) {
        std::string arg = argv[1];
        if (arg == "-h" || arg == "--help") {
            printUsage(argv[0]);
            return 0;
        }
        configPath = arg;
    }

    LOG_INFO("Starting Phased Array Radar Echo Simulator V3.0");
    LOG_INFO("Config file: " + configPath);

    // 注册信号处理
    std::signal(SIGINT, signalHandler);
    std::signal(SIGTERM, signalHandler);

    // 创建模拟器
    PhasedArrayRadarSimulator simulator;
    g_simulator = &simulator;

    // 初始化模拟器
    LOG_INFO("Initializing simulator...");
    if (!simulator.initialize(configPath)) {
        LOG_ERROR("Failed to initialize simulator");
        std::cerr << "Error: Failed to initialize simulator" << std::endl;
        return 1;
    }

    std::cout << "Simulator initialized successfully!" << std::endl;
    std::cout << "  - Radar frequency: " << simulator.getRadarParams().frequency / 1e9
              << " GHz" << std::endl;
    std::cout << "  - Bandwidth: " << simulator.getRadarParams().bandwidth / 1e6
              << " MHz" << std::endl;
    std::cout << "  - PRF: " << simulator.getRadarParams().prf << " Hz" << std::endl;
    std::cout << "  - Max range: " << simulator.getRadarParams().maxRange / 1e3
              << " km" << std::endl;
    std::cout << "  - Pulses per CPI: " << simulator.getRadarParams().numPulsesPerCPI
              << std::endl;
    std::cout << std::endl;

    // 添加示例目标（可选）
    TargetParams target1;
    target1.id = 1;
    target1.position = Position3D(10000, 0, 0);  // 10km
    target1.velocity = Velocity3D(-50, 0, 0);    // -50 m/s 径向
    target1.rcs_mean = 10.0;                      // 10 m^2
    target1.swerlingModel = SwerlingModel::Swerling1;
    target1.motionModel = MotionModel::ConstantVelocity;
    simulator.addTarget(target1);
    std::cout << "Added target 1 at 10km, moving at -50 m/s" << std::endl;

    TargetParams target2;
    target2.id = 2;
    target2.position = Position3D(15000, 5000, 0);  // ~15.8km
    target2.velocity = Velocity3D(0, -30, 0);       // -30 m/s 横向
    target2.rcs_mean = 100.0;                        // 100 m^2
    target2.swerlingModel = SwerlingModel::Swerling3;
    target2.motionModel = MotionModel::ConstantVelocity;
    simulator.addTarget(target2);
    std::cout << "Added target 2 at 15.8km, moving at -30 m/s" << std::endl;
    std::cout << std::endl;

    // 运行仿真
    std::cout << "Starting full simulation..." << std::endl;
    simulator.runFullSimulation();

    std::cout << "Simulation completed!" << std::endl;
    LOG_INFO("Simulation completed");

    // 清理
    g_simulator = nullptr;

    return 0;
}
